package permissions

import (
	"fmt"
	"go/ast"
	goparser "go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

type Permission struct {
	Name  string
	Value string
}

func ParsePath(path string) ([]Permission, error) {
	info, err := os.Stat(path)
	if err != nil {
		return nil, err
	}

	if !info.IsDir() {
		return parseFiles([]string{path})
	}

	var files []string
	err = filepath.Walk(path, func(current string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() || !isGoSourceFile(current) {
			return nil
		}

		files = append(files, current)
		return nil
	})
	if err != nil {
		return nil, err
	}

	sort.Strings(files)
	return parseFiles(files)
}

func Generate(typeName string, permissions []Permission) string {
	var sb strings.Builder

	sb.WriteString("// Code generated by go-struct-codegen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&sb, "export const %s = {\n", typeName)

	for _, permission := range permissions {
		fmt.Fprintf(&sb, "  %s: %q,\n", permission.Name, permission.Value)
	}

	fmt.Fprintf(&sb, "} as const;\n\n")
	fmt.Fprintf(&sb, "export type %s = typeof %s[keyof typeof %s];\n", typeName, typeName, typeName)

	return sb.String()
}

func parseFiles(paths []string) ([]Permission, error) {
	var permissions []Permission
	seen := map[string]bool{}

	for _, path := range paths {
		filePermissions, err := parseFile(path)
		if err != nil {
			return nil, err
		}

		for _, permission := range filePermissions {
			if seen[permission.Name] {
				continue
			}
			seen[permission.Name] = true
			permissions = append(permissions, permission)
		}
	}

	return permissions, nil
}

func parseFile(path string) ([]Permission, error) {
	fset := token.NewFileSet()
	file, err := goparser.ParseFile(fset, path, nil, 0)
	if err != nil {
		return nil, err
	}

	var permissions []Permission

	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.CONST {
			continue
		}

		inPermissionGroup := false
		for _, spec := range genDecl.Specs {
			valueSpec, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}

			if valueSpec.Type != nil {
				inPermissionGroup = isPermissionType(valueSpec.Type)
			}
			if !inPermissionGroup {
				continue
			}

			for i, name := range valueSpec.Names {
				if i >= len(valueSpec.Values) {
					continue
				}

				value, ok := stringLiteralValue(valueSpec.Values[i])
				if !ok {
					continue
				}

				permissions = append(permissions, Permission{
					Name:  name.Name,
					Value: value,
				})
			}
		}
	}

	return permissions, nil
}

func isPermissionType(expr ast.Expr) bool {
	switch value := expr.(type) {
	case *ast.SelectorExpr:
		return value.Sel.Name == "Permission"
	case *ast.Ident:
		return value.Name == "Permission"
	default:
		return false
	}
}

func stringLiteralValue(expr ast.Expr) (string, bool) {
	basicLit, ok := expr.(*ast.BasicLit)
	if !ok || basicLit.Kind != token.STRING {
		return "", false
	}

	value, err := strconv.Unquote(basicLit.Value)
	if err != nil {
		return "", false
	}

	return value, true
}

func isGoSourceFile(path string) bool {
	return strings.HasSuffix(path, ".go") && !strings.HasSuffix(path, "_test.go")
}
