package generator

import (
	"fmt"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/sladkoelllka/struct-codogen-ts/internal/parser"
)

const generatedHeader = "// Code generated by go-struct-codegen. DO NOT EDIT.\n\n"
const jsonValueTypeDef = "export type JsonValue = string | number | boolean | null | { [key: string]: JsonValue } | JsonValue[];\n\n"

// GeneratorConfig хранит настройки генерации TypeScript кода
type GeneratorConfig struct {
	ExportType string // Тип экспорта: "interface" или "type"
}

// Generator отвечает за преобразование Go структур в TypeScript типы
type Generator struct {
	config GeneratorConfig
}

// NewGenerator создает новый экземпляр генератора
func NewGenerator(config GeneratorConfig) *Generator {
	if config.ExportType == "" {
		config.ExportType = "interface"
	}

	return &Generator{config: config}
}

// generateFileContent генерирует TypeScript код из распарсенного Go файла.
func (g *Generator) generateFileContent(file *parser.File) string {
	var sb strings.Builder
	sb.WriteString(generatedHeader)
	if fileNeedsJSONValue(file) {
		sb.WriteString(jsonValueTypeDef)
	}

	nameMap := buildStructNameMap(file.Structs)
	emitted := map[string]bool{}

	for _, strct := range file.Structs {
		selfName := resolveStructName(strct, nameMap)
		if selfName == "" || emitted[selfName] {
			continue
		}

		g.generateStruct(&sb, strct, nameMap)
		emitted[selfName] = true
		sb.WriteString("\n")
	}

	return sb.String()
}

// generateStruct генерирует TypeScript interface/type для одной структуры
func (g *Generator) generateStruct(sb *strings.Builder, strct parser.Struct, nameMap map[string]string) {
	g.generateStructWithImports(sb, strct, nameMap, nil)
}

func (g *Generator) generateStructWithImports(sb *strings.Builder, strct parser.Struct, nameMap map[string]string, imports map[string]typeImport) {
	selfName := resolveStructName(strct, nameMap)
	if strct.AliasType != "" {
		if len(strct.Values) > 0 {
			fmt.Fprintf(sb, "export type %s = %s;\n", selfName, stringUnionType(strct.Values))
			return
		}
		fmt.Fprintf(sb, "export type %s = %s;\n", selfName, goTypeToTSWithImports(strct.AliasType, imports))
		return
	}

	var embedded []string
	for _, field := range strct.Fields {
		if !field.Embedded || field.JSONTag == "-" {
			continue
		}

		embedded = append(embedded, resolveEmbeddedName(strct.Package, field.Type, nameMap))
	}

	if g.config.ExportType == "interface" {
		if len(embedded) > 0 {
			fmt.Fprintf(sb, "export interface %s extends %s {\n", selfName, strings.Join(embedded, ", "))
		} else {
			fmt.Fprintf(sb, "export interface %s {\n", selfName)
		}
	} else {
		if len(embedded) > 0 {
			fmt.Fprintf(sb, "export type %s = %s & {\n", selfName, strings.Join(embedded, " & "))
		} else {
			fmt.Fprintf(sb, "export type %s = {\n", selfName)
		}
	}

	for _, field := range strct.Fields {
		if field.Embedded {
			continue
		}

		fieldName := resolveFieldName(field)
		if fieldName == "-" {
			continue
		}

		optional := ""
		if isOptionalField(field) {
			optional = "?"
		}

		fmt.Fprintf(sb, "  %s%s: %s;\n", fieldName, optional, goTypeToTSWithImports(field.Type, imports))
	}

	if g.config.ExportType == "interface" {
		sb.WriteString("}\n")
	} else {
		sb.WriteString("};\n")
	}
}

// FileOutput представляет сгенерированный TypeScript файл
type FileOutput struct {
	Path    string // Путь к файлу
	Content string // Содержимое файла
}

// GeneratePerFile генерирует отдельный TypeScript файл для каждого Go-файла
func (g *Generator) GeneratePerFile(files []*parser.File, outputDir string) []FileOutput {
	var result []FileOutput

	structToFile := buildStructToFileMap(files, outputDir)

	for _, file := range files {
		if !file.Generate {
			continue
		}

		filePath := outputPathForFile(file, outputDir)
		var sb strings.Builder
		sb.WriteString(generatedHeader)

		imports := collectImports(file, filePath, structToFile)
		writeImports(&sb, imports)
		if len(imports) > 0 {
			sb.WriteString("\n")
		}
		if fileNeedsJSONValue(file) {
			sb.WriteString(jsonValueTypeDef)
		}

		for _, strct := range file.Structs {
			g.generateStructWithImports(&sb, strct, nil, imports)
			sb.WriteString("\n")
		}

		result = append(result, FileOutput{Path: filePath, Content: sb.String()})
		if fileNeedsZod(file) {
			result = append(result, FileOutput{
				Path:    schemaOutputPathForFile(file, outputDir),
				Content: generateSchemaFileContent(file),
			})
		}
	}

	return result
}

func generateSchemaFileContent(file *parser.File) string {
	var sb strings.Builder
	sb.WriteString(generatedHeader)
	sb.WriteString("import { z } from 'zod';\n\n")

	for _, strct := range file.Structs {
		generateZodSchema(&sb, strct)
		if structNeedsZod(strct) {
			sb.WriteString("\n")
		}
	}

	return sb.String()
}

func stringUnionType(values []string) string {
	quotedValues := make([]string, 0, len(values))
	seen := make(map[string]bool, len(values))
	for _, value := range values {
		if seen[value] {
			continue
		}
		seen[value] = true
		quotedValues = append(quotedValues, strconv.Quote(value))
	}
	if len(quotedValues) == 0 {
		return "string"
	}
	return strings.Join(quotedValues, " | ")
}

func buildStructNameMap(structs []parser.Struct) map[string]string {
	nameMap := make(map[string]string, len(structs))
	usage := make(map[string]int, len(structs))

	for _, strct := range structs {
		usage[strct.Name]++
	}

	for _, strct := range structs {
		key := structKey(strct.Package, strct.Name)
		if usage[strct.Name] > 1 {
			nameMap[key] = toExportName(strct.Package, strct.Name)
		} else {
			nameMap[key] = strct.Name
		}
	}

	return nameMap
}

func buildStructToFileMap(files []*parser.File, outputDir string) map[string]string {
	structToFile := make(map[string]string)
	for _, file := range files {
		filePath := outputPathForFile(file, outputDir)
		for _, strct := range file.Structs {
			structToFile[file.Entity+"/"+strct.Name] = filePath
		}
	}
	return structToFile
}

type typeImport struct {
	ExportedName string
	LocalName    string
	Path         string
}

func collectImports(file *parser.File, filePath string, structToFile map[string]string) map[string]typeImport {
	imports := make(map[string]typeImport)
	localTypes := fileTypeNames(file)

	for _, strct := range file.Structs {
		if strct.AliasType != "" {
			addImport(imports, file, filePath, structToFile, localTypes, strct.AliasType)
		}

		for _, field := range strct.Fields {
			if field.JSONTag == "-" {
				continue
			}

			addImport(imports, file, filePath, structToFile, localTypes, field.Type)
		}
	}

	return imports
}

func fileTypeNames(file *parser.File) map[string]bool {
	names := make(map[string]bool, len(file.Structs))
	for _, strct := range file.Structs {
		names[strct.Name] = true
	}
	return names
}

func addImport(imports map[string]typeImport, file *parser.File, filePath string, structToFile map[string]string, localTypes map[string]bool, rawType string) {
	rawType = strings.TrimSpace(rawType)
	if rawType == "" {
		return
	}
	if strings.HasPrefix(rawType, "*") {
		addImport(imports, file, filePath, structToFile, localTypes, rawType[1:])
		return
	}
	if strings.HasPrefix(rawType, "[]") {
		addImport(imports, file, filePath, structToFile, localTypes, rawType[2:])
		return
	}
	if keyType, valueType, ok := mapType(rawType); ok {
		addImport(imports, file, filePath, structToFile, localTypes, keyType)
		addImport(imports, file, filePath, structToFile, localTypes, valueType)
		return
	}
	if baseType, typeArg, ok := genericType(rawType); ok {
		addImport(imports, file, filePath, structToFile, localTypes, baseType)
		addImport(imports, file, filePath, structToFile, localTypes, typeArg)
		return
	}

	targetKey := resolveStructFileKey(file, rawType)
	baseType := baseFieldType(rawType)
	target, ok := structToFile[targetKey]
	if !ok || target == filePath {
		return
	}

	relPath, err := filepath.Rel(filepath.Dir(filePath), target)
	if err != nil {
		return
	}
	if !strings.HasPrefix(relPath, ".") {
		relPath = "./" + relPath
	}
	relPath = filepath.ToSlash(relPath)

	localName := baseType
	if localTypes[baseType] {
		localName = importAliasName(rawType, baseType)
	}

	imports[baseType] = typeImport{
		ExportedName: baseType,
		LocalName:    localName,
		Path:         strings.TrimSuffix(relPath, ".ts"),
	}
}

func importAliasName(rawType, baseType string) string {
	if pkgRef, ok := packageRef(rawType); ok {
		return strings.Title(pkgRef) + baseType
	}
	return "Imported" + baseType
}

func resolveStructFileKey(file *parser.File, rawType string) string {
	baseType := baseFieldType(rawType)
	entity := file.Entity

	if pkgRef, ok := packageRef(rawType); ok {
		if importPath, exists := file.Imports[pkgRef]; exists {
			entity = extractEntityFromImportPath(importPath)
		}
	}

	return entity + "/" + baseType
}

func packageRef(rawType string) (string, bool) {
	rawType = strings.TrimPrefix(rawType, "*")
	rawType = strings.TrimPrefix(rawType, "[]")

	parts := strings.Split(rawType, ".")
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		return "", false
	}

	return parts[0], true
}

func extractEntityFromImportPath(importPath string) string {
	parts := strings.Split(importPath, "/")
	for i, part := range parts {
		if part == "handler" && i+1 < len(parts) {
			end := i + 1
			for end < len(parts) && parts[end] != "dto" {
				end++
			}
			if end > i+1 {
				return strings.Join(parts[i+1:end], "/")
			}
			return parts[i+1]
		}
	}

	for i, part := range parts {
		if part == "internal" && i+1 < len(parts) {
			return strings.Join(parts[i+1:], "/")
		}
		if part == "pkg" && i+1 < len(parts) {
			return strings.Join(parts[i:], "/")
		}
	}

	return "unknown"
}

func writeImports(sb *strings.Builder, imports map[string]typeImport) {
	typeNames := make([]string, 0, len(imports))
	for typeName := range imports {
		typeNames = append(typeNames, typeName)
	}
	sort.Strings(typeNames)

	for _, typeName := range typeNames {
		typeImport := imports[typeName]
		if typeImport.LocalName != typeImport.ExportedName {
			fmt.Fprintf(sb, "import type { %s as %s } from '%s';\n", typeImport.ExportedName, typeImport.LocalName, typeImport.Path)
			continue
		}
		fmt.Fprintf(sb, "import type { %s } from '%s';\n", typeImport.ExportedName, typeImport.Path)
	}
}

func outputPathForFile(file *parser.File, outputDir string) string {
	return filepath.Join(outputDir, file.Entity, file.Type+".ts")
}

func schemaOutputPathForFile(file *parser.File, outputDir string) string {
	return filepath.Join(outputDir, file.Entity, file.Type+".schema.ts")
}

func structKey(pkg, name string) string {
	return pkg + ":" + name
}

func resolveStructName(strct parser.Struct, nameMap map[string]string) string {
	if nameMap == nil {
		return strct.Name
	}

	if mapped, ok := nameMap[structKey(strct.Package, strct.Name)]; ok {
		return mapped
	}

	return strct.Name
}

func resolveEmbeddedName(pkg, name string, nameMap map[string]string) string {
	baseName := baseFieldType(name)
	if nameMap == nil {
		return baseName
	}

	if mapped, ok := nameMap[structKey(pkg, name)]; ok {
		return mapped
	}

	if mapped, ok := nameMap[structKey(pkg, baseName)]; ok {
		return mapped
	}

	return baseName
}

func resolveFieldName(field parser.Field) string {
	fieldName := field.JSONTag
	if fieldName == "" {
		fieldName = field.UriTag
	}
	if fieldName == "" {
		fieldName = field.FormTag
	}
	if fieldName == "" {
		fieldName = toJSFieldName(field.Name)
	}

	return strings.Split(fieldName, ",")[0]
}

func isOptionalField(field parser.Field) bool {
	return field.Optional || strings.HasPrefix(field.Type, "*") || tagHasOption(field.JSONTag, "omitempty")
}

func tagHasOption(tag, option string) bool {
	parts := strings.Split(tag, ",")
	for _, part := range parts[1:] {
		if strings.TrimSpace(part) == option {
			return true
		}
	}
	return false
}

func fileNeedsZod(file *parser.File) bool {
	for _, strct := range file.Structs {
		if structNeedsZod(strct) {
			return true
		}
	}

	return false
}

func fileNeedsJSONValue(file *parser.File) bool {
	for _, strct := range file.Structs {
		if structUsesJSONValue(strct) {
			return true
		}
	}

	return false
}

func structUsesJSONValue(strct parser.Struct) bool {
	if isJSONRawMessageType(strct.AliasType) {
		return true
	}

	for _, field := range strct.Fields {
		if isJSONRawMessageType(field.Type) {
			return true
		}
	}

	return false
}

func structNeedsZod(strct parser.Struct) bool {
	if strct.AliasType != "" {
		return false
	}

	for _, field := range strct.Fields {
		if field.Embedded {
			continue
		}
		if resolveFieldName(field) == "-" {
			continue
		}
		if field.Binding != "" {
			return true
		}
	}

	return false
}

func generateZodSchema(sb *strings.Builder, strct parser.Struct) {
	if !structNeedsZod(strct) {
		return
	}

	fmt.Fprintf(sb, "export const %sSchema = z.object({\n", strct.Name)
	for _, field := range strct.Fields {
		if field.Embedded {
			continue
		}

		fieldName := resolveFieldName(field)
		if fieldName == "-" {
			continue
		}

		fmt.Fprintf(sb, "  %q: %s,\n", fieldName, zodSchemaForField(field))
	}
	sb.WriteString("});\n")
}

func zodSchemaForField(field parser.Field) string {
	binding := parseBindingRules(field.Binding)
	baseType := strings.TrimPrefix(field.Type, "*")
	if strings.HasPrefix(baseType, "[]") {
		itemType := strings.TrimPrefix(baseType, "[]")
		itemSchema := applyBindingChain(initialZodType(itemType, binding.ItemRules), itemType, binding.ItemRules)
		schema := "z.array(" + itemSchema + ")"
		schema = applyBindingChain(schema, baseType, binding.BaseRules)
		if shouldOptionalize(field, binding) {
			schema += ".optional()"
		}
		return schema
	}

	schema := initialZodType(baseType, binding.BaseRules)
	schema = applyBindingChain(schema, baseType, binding.BaseRules)
	if shouldOptionalize(field, binding) {
		schema += ".optional()"
	}

	return schema
}

type parsedBinding struct {
	BaseRules []bindingRule
	ItemRules []bindingRule
}

type bindingRule struct {
	Name  string
	Value string
}

func parseBindingRules(binding string) parsedBinding {
	var result parsedBinding
	if binding == "" {
		return result
	}

	target := &result.BaseRules
	for _, part := range strings.Split(binding, ",") {
		part = strings.TrimSpace(part)
		if part == "" {
			continue
		}
		if part == "dive" {
			target = &result.ItemRules
			continue
		}

		name, value, hasValue := strings.Cut(part, "=")
		name = strings.TrimSpace(name)
		if name == "" {
			continue
		}
		rule := bindingRule{Name: name}
		if hasValue {
			rule.Value = strings.TrimSpace(value)
		}
		*target = append(*target, rule)
	}

	return result
}

func shouldOptionalize(field parser.Field, binding parsedBinding) bool {
	if hasBindingRule(binding.BaseRules, "required") {
		return false
	}
	if strings.HasPrefix(field.Type, "*") {
		return true
	}
	return hasBindingRule(binding.BaseRules, "omitempty") || tagHasOption(field.JSONTag, "omitempty")
}

func hasBindingRule(rules []bindingRule, name string) bool {
	for _, rule := range rules {
		if rule.Name == name {
			return true
		}
	}
	return false
}

func initialZodType(goType string, rules []bindingRule) string {
	if strings.TrimSpace(goType) == "string" && hasBindingRule(rules, "email") {
		return "z.email()"
	}

	return baseZodType(goType)
}

func baseZodType(goType string) string {
	switch strings.TrimSpace(goType) {
	case "string":
		return "z.string()"
	case "int", "int8", "int16", "int32", "int64":
		return "z.number().int()"
	case "uint", "uint8", "uint16", "uint32", "uint64":
		return "z.number().int().nonnegative()"
	case "float32", "float64":
		return "z.number()"
	case "bool":
		return "z.boolean()"
	case "time.Time", "Time":
		return "z.string()"
	case "json.RawMessage", "RawMessage":
		return "z.json()"
	default:
		return "z.unknown()"
	}
}

func isJSONRawMessageType(goType string) bool {
	goType = strings.TrimSpace(goType)
	goType = strings.TrimPrefix(goType, "*")
	return goType == "json.RawMessage" || goType == "RawMessage"
}

func applyBindingChain(schema, goType string, rules []bindingRule) string {
	for _, rule := range rules {
		switch rule.Name {
		case "required", "omitempty":
			continue
		case "email":
			continue
		case "min":
			schema += ".min(" + renderScalarValue(rule.Value) + ")"
		case "max":
			schema += ".max(" + renderScalarValue(rule.Value) + ")"
		case "gt":
			schema += ".gt(" + renderScalarValue(rule.Value) + ")"
		case "gte":
			schema += ".gte(" + renderScalarValue(rule.Value) + ")"
		case "lt":
			schema += ".lt(" + renderScalarValue(rule.Value) + ")"
		case "lte":
			schema += ".lte(" + renderScalarValue(rule.Value) + ")"
		case "oneof":
			schema = renderOneOfSchema(goType, rule.Value)
		}
	}

	return schema
}

func renderOneOfSchema(goType, value string) string {
	options := strings.Fields(strings.TrimSpace(value))
	if len(options) == 0 {
		return baseZodType(goType)
	}

	var literals []string
	for _, option := range options {
		literals = append(literals, "z.literal("+renderTypedLiteral(goType, option)+")")
	}

	if len(literals) == 1 {
		return literals[0]
	}

	return "z.union([" + strings.Join(literals, ", ") + "])"
}

func renderTypedLiteral(goType, value string) string {
	goType = strings.TrimPrefix(goType, "*")
	goType = strings.TrimPrefix(goType, "[]")

	switch goType {
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"float32", "float64":
		return renderScalarValue(value)
	case "bool":
		if value == "true" || value == "false" {
			return value
		}
		return "false"
	default:
		return strconv.Quote(value)
	}
}

func renderScalarValue(value string) string {
	if value == "" {
		return "true"
	}

	if intValue, err := strconv.ParseInt(value, 10, 64); err == nil {
		return strconv.FormatInt(intValue, 10)
	}

	if floatValue, err := strconv.ParseFloat(value, 64); err == nil {
		return strconv.FormatFloat(floatValue, 'f', -1, 64)
	}

	return strconv.Quote(value)
}

func baseFieldType(fieldType string) string {
	fieldType = strings.TrimPrefix(fieldType, "*")
	fieldType = strings.TrimPrefix(fieldType, "[]")
	if before, _, ok := strings.Cut(fieldType, "["); ok {
		fieldType = before
	}
	if strings.Contains(fieldType, ".") {
		parts := strings.Split(fieldType, ".")
		fieldType = parts[len(parts)-1]
	}
	return fieldType
}

func toExportName(pkg, name string) string {
	if pkg == "" {
		return strings.Title(name)
	}

	return strings.Title(pkg) + strings.Title(name)
}

// goTypeToTS преобразует Go тип в TypeScript тип
func goTypeToTS(goType string) string {
	return goTypeToTSWithImports(goType, nil)
}

func goTypeToTSWithImports(goType string, imports map[string]typeImport) string {
	goType = strings.TrimSpace(goType)

	if strings.HasPrefix(goType, "*") {
		goType = goType[1:]
	}

	if strings.HasPrefix(goType, "[]") {
		return goTypeToTSWithImports(goType[2:], imports) + "[]"
	}

	if keyType, valueType, ok := mapType(goType); ok {
		return "Record<" + recordKeyType(keyType, imports) + ", " + goTypeToTSWithImports(valueType, imports) + ">"
	}

	if baseType, typeArg, ok := genericType(goType); ok {
		return goTypeToTSWithImports(baseType, imports) + "<" + goTypeToTSWithImports(typeArg, imports) + ">"
	}

	switch goType {
	case "string":
		return "string"
	case "int", "int8", "int16", "int32", "int64":
		return "number"
	case "uint", "uint8", "uint16", "uint32", "uint64":
		return "number"
	case "float32", "float64":
		return "number"
	case "bool":
		return "boolean"
	case "time.Time", "Time":
		return "string | Date"
	case "json.RawMessage", "RawMessage":
		return "JsonValue"
	case "interface{}":
		return "any"
	case "any":
		return "any"
	default:
		if strings.Contains(goType, ".") {
			parts := strings.Split(goType, ".")
			typeName := parts[len(parts)-1]
			if typeImport, ok := imports[typeName]; ok {
				return typeImport.LocalName
			}
			return typeName
		}

		return goType
	}
}

func mapType(goType string) (string, string, bool) {
	goType = strings.TrimSpace(goType)
	if !strings.HasPrefix(goType, "map[") {
		return "", "", false
	}

	end := matchingBracketIndex(goType, 3)
	if end < 0 || end+1 >= len(goType) {
		return "", "", false
	}

	keyType := strings.TrimSpace(goType[4:end])
	valueType := strings.TrimSpace(goType[end+1:])
	if keyType == "" || valueType == "" {
		return "", "", false
	}

	return keyType, valueType, true
}

func matchingBracketIndex(value string, open int) int {
	if open < 0 || open >= len(value) || value[open] != '[' {
		return -1
	}

	depth := 0
	for i := open; i < len(value); i++ {
		switch value[i] {
		case '[':
			depth++
		case ']':
			depth--
			if depth == 0 {
				return i
			}
		}
	}

	return -1
}

func recordKeyType(goType string, imports map[string]typeImport) string {
	keyType := goTypeToTSWithImports(goType, imports)
	switch keyType {
	case "string", "number", "symbol":
		return keyType
	}

	if strings.Contains(keyType, "|") || strings.Contains(keyType, "&") || strings.Contains(keyType, "[]") {
		return "string"
	}

	return keyType
}

func genericType(goType string) (string, string, bool) {
	start := strings.Index(goType, "[")
	if start < 0 || !strings.HasSuffix(goType, "]") {
		return "", "", false
	}

	baseType := strings.TrimSpace(goType[:start])
	typeArg := strings.TrimSpace(strings.TrimSuffix(goType[start+1:], "]"))
	if baseType == "" || typeArg == "" || strings.Contains(typeArg, ",") {
		return "", "", false
	}

	return baseType, typeArg, true
}

// toJSFieldName преобразует имя Go поля в camelCase (JavaScript стиль)
func toJSFieldName(name string) string {
	if len(name) == 0 {
		return name
	}

	return strings.ToLower(name[:1]) + name[1:]
}
