package errorcodes

import (
	"fmt"
	"go/ast"
	goparser "go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

type Code struct {
	Name  string
	Value string
}

var defaultCodes = []Code{
	{Name: "ErrBadRequest", Value: "BAD_REQUEST"},
	{Name: "ErrUnauthorized", Value: "UNAUTHORIZED"},
	{Name: "ErrForbidden", Value: "FORBIDDEN"},
	{Name: "ErrNotFound", Value: "NOT_FOUND"},
	{Name: "ErrConflict", Value: "CONFLICT"},
	{Name: "ErrTooManyRequests", Value: "TOO_MANY_REQUESTS"},
	{Name: "ErrInternal", Value: "INTERNAL_SERVER_ERROR"},
}

func ParsePath(path string) ([]Code, error) {
	info, err := os.Stat(path)
	if err != nil {
		return nil, err
	}

	if !info.IsDir() {
		return parseFiles([]string{path})
	}

	var files []string
	err = filepath.Walk(path, func(current string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() || !isGoSourceFile(current) {
			return nil
		}

		files = append(files, current)
		return nil
	})
	if err != nil {
		return nil, err
	}

	sort.Strings(files)
	return parseFiles(files)
}

func Generate(codes []Code) string {
	var sb strings.Builder

	sb.WriteString("// Code generated by go-struct-codegen. DO NOT EDIT.\n\n")
	sb.WriteString("export const ErrorCode = {\n")

	for _, code := range defaultCodes {
		fmt.Fprintf(&sb, "  %s: %q,\n", code.Name, code.Value)
	}
	for _, code := range codes {
		fmt.Fprintf(&sb, "  %s: %q,\n", code.Name, code.Value)
	}

	sb.WriteString("} as const;\n\n")
	sb.WriteString("export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode];\n")

	return sb.String()
}

func parseFiles(paths []string) ([]Code, error) {
	constValues := map[string]string{}
	var orderedCodes []Code
	seen := map[string]bool{}

	for _, path := range paths {
		fileConstValues, err := parseConstValues(path)
		if err != nil {
			return nil, err
		}
		for name, value := range fileConstValues {
			constValues[name] = value
		}
	}

	for _, path := range paths {
		fileCodes, err := parseVarCodes(path, constValues)
		if err != nil {
			return nil, err
		}
		for _, code := range fileCodes {
			if seen[code.Name] {
				continue
			}
			seen[code.Name] = true
			orderedCodes = append(orderedCodes, code)
		}
	}

	return orderedCodes, nil
}

func parseConstValues(path string) (map[string]string, error) {
	fset := token.NewFileSet()
	file, err := goparser.ParseFile(fset, path, nil, 0)
	if err != nil {
		return nil, err
	}

	result := map[string]string{}

	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.CONST {
			continue
		}

		inErrorCodeGroup := false
		for _, spec := range genDecl.Specs {
			valueSpec, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}

			if valueSpec.Type != nil {
				inErrorCodeGroup = isErrorCodeType(valueSpec.Type)
			}
			if !inErrorCodeGroup {
				continue
			}

			for i, name := range valueSpec.Names {
				if i >= len(valueSpec.Values) {
					continue
				}

				value, ok := stringLiteralValue(valueSpec.Values[i])
				if !ok {
					continue
				}

				result[name.Name] = value
			}
		}
	}

	return result, nil
}

func parseVarCodes(path string, constValues map[string]string) ([]Code, error) {
	fset := token.NewFileSet()
	file, err := goparser.ParseFile(fset, path, nil, 0)
	if err != nil {
		return nil, err
	}

	var codes []Code

	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.VAR {
			continue
		}

		for _, spec := range genDecl.Specs {
			valueSpec, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}

			for i, name := range valueSpec.Names {
				if i >= len(valueSpec.Values) {
					continue
				}

				codeConstName, ok := extractCodeConstName(valueSpec.Values[i])
				if !ok {
					continue
				}

				codeValue, ok := constValues[codeConstName]
				if !ok {
					continue
				}

				codes = append(codes, Code{
					Name:  name.Name,
					Value: codeValue,
				})
			}
		}
	}

	return codes, nil
}

func extractCodeConstName(expr ast.Expr) (string, bool) {
	compositeLit, ok := expr.(*ast.CompositeLit)
	if !ok {
		return "", false
	}

	if !isErrType(compositeLit.Type) {
		return "", false
	}

	for _, elt := range compositeLit.Elts {
		keyValue, ok := elt.(*ast.KeyValueExpr)
		if !ok {
			continue
		}

		keyIdent, ok := keyValue.Key.(*ast.Ident)
		if !ok || keyIdent.Name != "Code" {
			continue
		}

		switch value := keyValue.Value.(type) {
		case *ast.Ident:
			return value.Name, true
		case *ast.SelectorExpr:
			return value.Sel.Name, true
		}
	}

	return "", false
}

func isErrorCodeType(expr ast.Expr) bool {
	switch value := expr.(type) {
	case *ast.SelectorExpr:
		return value.Sel.Name == "ErrorCode"
	case *ast.Ident:
		return value.Name == "ErrorCode"
	default:
		return false
	}
}

func isErrType(expr ast.Expr) bool {
	switch value := expr.(type) {
	case *ast.SelectorExpr:
		return value.Sel.Name == "Type"
	case *ast.Ident:
		return value.Name == "Type"
	default:
		return false
	}
}

func stringLiteralValue(expr ast.Expr) (string, bool) {
	basicLit, ok := expr.(*ast.BasicLit)
	if !ok || basicLit.Kind != token.STRING {
		return "", false
	}

	value, err := strconv.Unquote(basicLit.Value)
	if err != nil {
		return "", false
	}

	return value, true
}

func isGoSourceFile(path string) bool {
	return strings.HasSuffix(path, ".go") && !strings.HasSuffix(path, "_test.go")
}
